// Roughly how athlete data that we're pushing to the Athletes contract should be formatted

module.exports = [
  // possible attribute "points"
  { name: 'Abbedagge', id: 0, description: "Abbedagge plays mid laner for 100 Thieves. His ID comes from a unit's sound in Age of Empires. He was awarded NA 2nd All Pro Team in Summer 2021." },
  { name: 'Ablazeolive', id: 1, description: "Ablazeolive plays mid laner for Golden Guardians. He is known for his play on control mages and breakout performance in the 2021 LCS on champs like Zoe and Lucian." },
  { name: 'aphromoo', id: 2 },
  { name: 'Berserker', id: 3 },
  { name: 'Biofrost', id: 4 },
  { name: 'Bjergsen', id: 5 },
  { name: 'Blaber', id: 6 },
  { name: 'Blue', id: 7 },
  { name: 'Bwipo', id: 8 },
  { name: 'Closer', id: 9 },
  { name: 'Contractz', id: 10 },
  { name: 'CoreJJ', id: 11 },
  { name: 'Danny', id: 12 },
  { name: 'IgNar', id: 13 },
  { name: 'Gamsu', id: 14 },
  { name: 'FBI', id: 15 },
  { name: 'Jensen', id: 16 },
  { name: 'Hans sama', id: 17 },
  { name: 'huhi', id: 18 },
  { name: 'Shenyi', id: 19 },
  { name: 'Impact', id: 20 },
  { name: 'Inspired', id: 21 },
  { name: 'Zven', id: 22 },
  { name: 'Jenkins', id: 23 },
  { name: 'Johnsun', id: 24 },
  { name: 'jojopyun', id: 25 },
  { name: 'Josedeodo', id: 26 },
  { name: 'Kumo', id: 27 },
  { name: 'Licorice', id: 28 },
  { name: 'Lost', id: 29 },
  { name: 'Luger', id: 30 },
  { name: 'Neo', id: 31 },
  { name: 'Olleh', id: 32 },
  { name: 'Palafox', id: 33 },
  { name: 'Poome', id: 34 },
  { name: 'PowerOfEvil', id: 35 },
  { name: 'Pridestalker', id: 36 },
  { name: 'Revenge', id: 37 },
  { name: 'River', id: 38 },
  { name: 'Santorin', id: 39 },
  { name: 'Huni', id: 40 },
  { name: 'Tactical', id: 41 },
  { name: 'Ssumday', id: 42 },
  { name: 'Fudge', id: 43 },
  { name: 'Spica', id: 44 },
  { name: 'Maple', id: 45 },
  { name: 'toucouille', id: 46 },
  { name: 'Vulcan', id: 47 },
  { name: 'Arrow', id: 48 },
  { name: 'Kenvi', id: 49 }
];
